### ISSUE TITLE
logging(): no warning output's, if no -v (verbose) is selected

### ISSUE THREAD

**Issue by mgafner** [fadecut/fadecut#11]
how to reproduce this?

**Comment by mgafner** [comment]
i have no clue what to do with this... anyone? i'm going to close this issue...

**Comment by micressor** [comment]
May be this one has impact to #31 according to this commit 21fe9d3ef43e4569eabfafcd14ca0e0bb5f095b4?

**Comment by mgafner** [comment]
this is fixed now. verbose mode can be set from profile with VERBOSE=1 and it can be overwritten from commandline with option -v
