### ISSUE TITLE
Testframework: take testing upstream code directly from git

### ISSUE THREAD

**Issue by mgafner** [fadecut/fadecut#12]

**Comment by micressor** [comment]
I am not sure, if we can arrange that with debian buildpackage process. Have to clarify.

**Comment by micressor** [comment]
What's exactly the goal of this task? ;) Let's define...

**Comment by mgafner** [comment]
no idea... i guess you wrote this task in the todo file a while ago... ;-)

**Comment by micressor** [comment]
I think we don't need it. We can reopen again, if there is any case for it. At the moment I think not. :)
