### ISSUE TITLE
mp3Encoding/oggEncoding reduces to an under-bitrate

### ISSUE THREAD

**Issue by micressor** [fadecut/fadecut#19]
Das wahrscheinlich größte Problem ist derzeit (Version: fadecut 0.1.1-1) die Reduzierung der Bitrate von MP3-Dateien, auch wenn der Stream eine höhere Qualität bietet. Da fadecut den Encoder LAME ohne entsprechende Option aufruft, wird bei der Kodierung nur die Standard-Bitrate von 128 kbps benutzt. Idealerweise müsste zuerst die Bitrate des Streams ermittelt werden (Streamripper erkennt diese) und bei der anschließenden Kodierung berücksichtigt werden.

Als Workaround kann man die Funktion mp3Encoding ändern und den Aufruf von lame um die gewünschte Bitrate bzw. Qualitätsstufe ergänzen. Dies setzt natürlich voraus, dass die Bitrate des Streams vorher bekannt ist. Da aber nicht alle Streams mit der gleichen Bitrate gesendet werden, ist ein fester Wert in der Praxis eher hinderlich, wenn man verschiedene Internetradios aufzeichnen möchte (verursacht aber auch kein dramatisches Problem).

Diese Problematik betrifft prinzipiell auch die Speicherung als OGG-Datei. Abhilfe schafft eine manuelle Änderung der Funktion oggEncoding. Der entsprechende Parameter ist im Artikel Vorbis beschrieben.

Found that on [ubuntuusers.de](http://wiki.ubuntuusers.de/fadecut#Bitrate-wird-reduziert).

**Comment by mgafner** [comment]
how to detect the bitrate of ripped files:
http://askubuntu.com/questions/196890/how-to-find-the-bitrate-of-an-mp3-file-via-command-line

* simplest: file . but it probably does not give the correct value for VBR encoded files
* mp3info
* mediainfo

**Comment by mgafner** [comment]
habe mich für mediainfo entschieden, weil dieses uns gleich für mehrere Medienformate Infos liefern kann.

**Comment by mgafner** [comment]
Ist implementiert und darf jetzt getestet werden ;-)

**Comment by mgafner** [comment]
i'm not yet happy with this. what happens when source is a VBR encoded mp3? i have to test this out. but for this i have to fix issue #28 first.

**Comment by mgafner** [comment]
okay... is tested. lame takes the closest lower available constant bitrate and oggenc is encoding with exactly the same bitrate as the source. so this is done now.
