### ISSUE TITLE
Think and decide about version numbers

### ISSUE THREAD

**Issue by mgafner** [fadecut/fadecut#22]
Ich habe einen Milestone für 0.2.0 erfasst. Das kommt noch aus dem Todo-File, wo wir einige Todo's auf 0.2.0 terminiert haben.

Wie gehen wir weiter? 0.3 - 0.4 - 0.5 ? Was wollen wir auf die Version 1.0 hin erreichen?

**Comment by micressor** [comment]
0.X - Features
0.X.X Bufixes des release 0.X?

**Comment by micressor** [comment]
Je nachdem, wieviel neue Features es seit dem letzten Release gibt, machen wir 0.{3,4,5,?} ?

**Comment by micressor** [comment]
Have a look at [milestones](https://github.com/fadecut/fadecut/milestones).

**Comment by mgafner** [comment]
okay for me ;-) let's close this issue
