### ISSUE TITLE
catch error: "can't resolve hostname"

### ISSUE THREAD

**Issue by mgafner** [fadecut/fadecut#40]
catch such errors:
        streamripper http://club-high.rautemusik.fm/listen.pls
        Connecting...
        error -6 [SR_ERROR_CANT_RESOLVE_HOSTNAME]
        bye..
        shutting down

(taken from TODO.md)

**Comment by mgafner** [comment]
master head version looks like this:
```
21:25:32 Info:     Loading master profile: /home/mgafner/.fadecut/fadecutrc
21:25:32 Info:     Loading profile: /home/mgafner/.fadecut/profiles/swisspop
21:25:32 Success:  /usr/bin/streamripper started pid=10748
21:25:34 Error:    Streamripper exited with error -6 [SR_ERROR_CANT_RESOLVE_HOSTNAME]
```
looks like working as expected.

what else do we need to do @micressor ? I think we can close this issue.

**Comment by micressor** [comment]
If exit code of fadecut is also correct, we can close this one. yeah.

**Comment by micressor** [comment]
Tested! This is behaviour is ok.
