### ISSUE TITLE
Output directory not automatically created

### ISSUE THREAD

**Issue by micressor** [fadecut/fadecut#51]
Should directory `./new` created if it does not exist?

```
$ fadecut -r -p test
11:57:11 Info:     Loading profile: /home/user/.fadecut/profiles/test
11:57:11 Error:    /home/user/Downloads/new: Output directory does not exist
```

To mee it looks like a bug.

**Comment by micressor** [comment]
@mgafner What you mean?

**Comment by mgafner** [comment]
yes, there was half made work already towards to this. i just had to delete old code. now fixed.
