### ISSUE TITLE
Fadecut should keep the original time stamps of downloaded files

### ISSUE THREAD

**Issue by dances-with-clouds** [fadecut/fadecut#55]
The program uses this loop to do its work on each file:

FILES=*.mp3
...
cd "$WORKDIR"
for F in $FILES
do

This loop ignores and destroys the time stamps of downloaded files. After fadecut has accessed the files, each one has a new time stamp of fadecut's accessing it and sorting the resulting files by date is no longer possible. 

This could easily be avoided by using "cp -p" whenever a file is copied and adding statements like this to the loop:

for F in $FILES
do
     TIMESTAMP=$(date -R -r "$F")

*before* the file is modified in any way and 

   touch -d "$TIMESTAMP" "$OUTPUTDIR/$Fdst"

after each and every function/command that changes the time stamp, including id3v2:

       id3v2 -C "$F" > /dev/null 2>&1
        touch -d "$TIMESTAMP" "$F"

If there is a more elegant way to do this, I am willing to learn. :)

**Comment by mgafner** [comment]
Thanks for the issue. You're absolutely right, the timestamps should be always the original. I'm going into this.

**Comment by dances-with-clouds** [comment]
You're welcome!

By the way: when I took a look into the script, I also found two or three occurrences of $F without being put in quotes. To avoid confusion caused by spaces as part of the file name, either those variables holding file names should always be inside quotes, or you need to set $IFS to new line exclusively, like this:

OLD_IFS=$IFS
IFS=$'\n'

Later, when needed, you can easily restore the original:

IFS=$OLD_IFS

I am sorry if this sounds like a schoolmaster to you, that is not my intention! File names that contain spaces have driven me mad times enough, so I am talking out of experience. :)

**Comment by mgafner** [comment]
no problem with teaching :-) usually we put quotes but it looks like we forgot two or three.

i updated fadecut and the timestamps should be well preserved now. thanks for your contribution!
