### ISSUE TITLE
Folder "dontlike": exclude artists completly

### ISSUE THREAD

**Issue by wehkah** [fadecut/fadecut#56]
It would be nice if there was an option to exclude artists completely, no matter which song they are singing. 

And vice versa: songs should be exclude-able, regardless of the artist who's singing it.

**Comment by mgafner** [comment]
Thanks for the issue. 

Yes why not. We can do that. We could add a new option in fadecutrc where we add excludes. Excluded songs would be downloaded anyway and automatically moved in the dontlike folder.

**Comment by dances-with-clouds** [comment]
If I may make a humble suggestion: until now there no artist in the world called "@@@" and there's no song in the world called "~~~". So maybe you could just use something like these inside the dontlike folder:

artists name - ~~~.mp3  
@@@ - song title.mp3

The first one can tell fadecut to ignore any song by this artist, and the second one can cause fadecut to ignore the song, no matter who performs it.

Of cause you would have to deal with this problem again, whenever the first artist called "@@@" releases a song called "~~~". But I doubt that this will happen while human kind still exists. ;)

**Comment by mgafner** [comment]
why not to put as setting in the profile file? something like:
exclude_artists=alpha beta gamma
exclude_titles=one title, another title

**Comment by wehkah** [comment]
Certainly, that is also a good idea! But beware: the excluded artists and titles need to be separated by a character, that will not appear as part of a song title or an artist's name. Spaces, colons, commas, periods, question marks, exclamation marks and many more, even parenthesis, do not qualify for this purpose!

**Comment by wehkah** [comment]
Suggestion: 

Instead of a folder containing unwanted songs, FC could use a text file that contains those song titles and artists' names. Using a text file would eliminate all the trouble that come with using wild cards like "*" or "?", or any other special characters that are part of the artists name or the song title, which are not allowed by the underlying operating system. Furthermore, it would be independent of the system's local character set (UTF, ISO-xxx, etc).

Eg, the contents of such a file could look like this:

```
artist number one - this song
artist number two - this song, too
this artist I don't like at all - *
* - thit silly song, no matter who's performing!


```

**Comment by mgafner** [comment]
good suggestion! As I understood from your first posts you have some experience in bash scripting?! Maybe you want to write a pull request?

**Comment by wehkah** [comment]
Maybe I would like to do so... if I knew, what you are talking about... What is a "pull request"?

**Comment by wehkah** [comment]
By the way: checking the contents of such a file to check the occurrence of a certain artist or a certain song, or the combination of both, would be a simple matter of doing something like "grep $song $file".

Wright now I am not sure how to grep for an actual wild card, but I think it must be "escaped", so 

```
grep "$artist - $songtitle" $file
grep "\* - $songtitle" $file 
grep "$artist - \*" $file
```

should do the trick.

**Comment by mgafner** [comment]
> Maybe I would like to do so... if I knew, what you are talking about... What is a "pull request"?

1. fork our project: https://help.github.com/articles/fork-a-repo/ 
2. write your new feature in your local clone
3. create the pull request: https://help.github.com/articles/about-pull-requests/

**Comment by wehkah** [comment]
I will give it a try, but I need some time. 

For the moment I have written some own scripts that use streamripper, a modified version of fadecut and exiftools to download, cut and rename songs from internet stations, burn the songs onto a cd or copy them onto a USB stick, all in one go.

I think I will publish those scripts, I am sure, they will come handy for other users as well. And along with those scripts I will publish the modified version of fadecut as well.

While waiting for my scripts...

I think this could be the solution to the above issue:


```
 DONTLIKE="$PROFILEDIR/dontlike
 ...
 # do some checks, check if file already exists and set status
  # status will be written to statslog
  # depending on status the processing will continue or will skipped to next file
  if [[ -z $ARTIST ]] || [[ -z $TITLE ]]
  then
  ...
  elif [ "xxx$(grep "$ARTIST - \*" $DONTLIKE)" != "xxx" ]  || [ "xxx$(grep "\* - $TITLE" $DONTLIKE)" != "xxx" ] || [ "xxx$(grep "$ARTIST - $TITLE" $DONTLIKE)" != "xxx" ] ; then
    logging -i "I don't like. File exists in $DONTLIKEDIR -> deleting ..."
    rm "$F"
    Fstatus="dontlike"
  fi

```

**Comment by wehkah** [comment]
Just in case you're interested: 

While working on my own scripts, I discovered that this solution works the best (at least at my machine):
```

DONTLIKE="$PROFILEDIR/dontlike"
...
  # do some checks, check if file already exists and set status
  # status will be written to statslog
  # depending on status the processing will continue or will skipped to next file
thissong=$(grep -i "\* - $TITLE" $DONTLIKE)
thisartist=$(grep -i "$ARTIST - \*" $DONTLIKE)
thissongbythisartist=$(grep -i "$ARTIST - $TITLE" $DONTLIKE)

if [[ -z $ARTIST ]] || [[ -z $TITLE ]] 
then
 ...
elif ...
elif ...
elif [ "xxx${thissong}" != "xxx" ] ; then
	echo "I don't like this song at all. It's listed in $DONTLIKE -> deleting..."
	rm "$F"
	Fstatus="dontlike"
  elif  [ "xxx${thisartist}" != "xxx" ] ; then
	echo "I don't like this artist. He/she is listed in $DONTLIKE -> deleting..."
	rm "$F"
	Fstatus="dontlike"
  elif  [ "xxx${thissongbythisartist}" != "xxx" ] ; then
	echo "I don't like this song by this artist. It's listed in $DONTLIKE -> deleting..."
	rm "$F"
	Fstatus="dontlike"
  fi

```

I also deleted the function "filerename", which turns file names to lower cases only and replaces spaces by underscore. I did this because I did not really see any urgent need for these replacements. Your mileage may differ, of cause! But after all: we're living in the 21st century and any OS and any device that can't deal with upper/lower-case and spaces as part of file names shouldn't be used any longer.

**Comment by wehkah** [comment]
I have to admit the forking process is a bit too complicated to me. :(

So I'll just attach my modified version of fadecut to this message. If you run a diff, you will see the differences. I've used this modified version for some days now and I have not run into trouble with it. On the other hand, you, being the expert here, will surely find things that can be improved. 

In the mean time I have written a small script that acts as a wrapper for fadecut and streamripper: it starts those programs to download and reshape songs, and burns them onto a CD or copies them to a USB drive in one go. It can also be called by udev to start the copying or the burning process on a headless machine. 

If you would like to have a view at this script, let me know where to send it. 

[fadecut.modified.gz](https://github.com/fadecut/fadecut/files/1272781/fadecut.modified.gz)

**Comment by mgafner** [comment]
@dances-with-clouds : thank you for the contribution of your modified version of fadecut. 

if you want to publish your script to open source we are glad to hear about it ;)

**Comment by wehkah** [comment]
Done! :)

**Comment by mgafner** [comment]
yep, thx! ;-)
